version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - '13306:3306'
    environment: # -e 옵션
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
  redis:
    image: redis
    container_name: redis
    ports:
      - 16379:6379
    restart: on-failure
  main-server:
    container_name: main-server
    build: .
    command: sh -c "./entrypoint.dev.sh"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - redis
      - mongo
